name: Dev Workflow

on:
  paths:
  - "envs/dev/**"

  workflow_dispatch:

jobs:
  deploying-to-localstack:
    name: Deploying to LocalStack
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev

    steps:
    - name: Running checkout
      uses: actions/checkout@v6

    - name: Setting up python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Running Python unit tests
      run: python -m unittest
      working-directory: ./modules/lambda/test

    - name: Start LocalStack
      uses: LocalStack/setup-localstack@v19cb04b7695736b30be27d4673d721086f5d1748
      with:
        image-tag: 'latest'
        use-pro: false
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

    - name: Set up tflocal
      run: pip install terraform-local

    - name: Running tflocal plan
      run: tflocal plan -var-file=dev.tfvars

    - name: Running tflocal apply
      run: tflocal apply -var-file=dev.tfvars